version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/workspace/app
      - /workspace/app/node_modules
      - ./rust:/workspace/rust
    environment:
      - NODE_ENV=development
